services:
  - type: web
    name: capcut-guide
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    domains:
      - zenkycut.com
    envVars:
      - key: PORT
        value: 3000
